services:
  flask:
    restart: no
    build: ./web
    ports:
      - 8000:8000
    env_file:
      - web/.env


  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d/app.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - flask
